### ISSUE TITLE
Client Side redirect avoid page refresh

### ISSUE THREAD

**Issue by juanfranblanco** [henalbrod/Blazor.Auth0#23] opened 2019-09-13 16:04 UTC
Hi,

First of all, your library is fantastic.

I am trying to integrate in the http://playground.nethereum.com as a client side github social authentication to publish gist to github, but when login in / authenticating the user you have to reload the whole blazor application.

I have seen that you use iframes to logout of the applications, is this something you are considering to enable login in? 

Any other thoughts / ideas ?

Many thanks in advance

**Comment by henalbrod** [comment] 2019-09-13 16:45
Hi,

Thanks!

What you're commenting is true, the whole application is reloaded but this is the expected behavior because the user should log in via Github login.

Now, this should happen only if the users haven't login in the past or logged off the application. For already authenticated users it should be transparent, as the library utilizes silent login (login via hidden iframe) that detects if the user has an active session in the background.

In the case of reloading the app (even one time) is still a no-go, we would have an opportunity by implementing Pop Up Mode (not supported yet by this library) and in the meantime, we would work to see if we can implement a less disruptive authentication flow. Sounds like a plan?

**Comment by juanfranblanco** [comment] 2019-09-13 17:26
Many thanks for the quick response.

Yes, that will be great as the users will only login on adhoc basis, so reloading the application will confuse them (and potentially lose their state)

Also, regarding silent login, I had to set:
 options.RequireAuthenticatedUser = false;
as am getting a 400 error. Do you have any thoughts on that?

**Comment by henalbrod** [comment] 2019-09-13 18:30
It means that setting RequireAuthenticatedUser to false let's you to authenticate otherwise don't?

**Comment by juanfranblanco** [comment] 2019-09-13 20:45
Correct

**Comment by henalbrod** [comment] 2019-09-19 02:21
Hi!

v1.0.0.Preview2 is now released, would you mind giving it a try to see if the error 400 persist?

**Comment by henalbrod** [comment] 2019-09-25 02:52
Hi, v1.0.0.Preview3 is now live, would you give it a try, please?

**Comment by juanfranblanco** [comment] 2019-09-25 05:39
Sure, apologies I did see your message but did not respond. Ill check today.

**Comment by henalbrod** [comment] 2019-11-04 02:25
Hi @juanfranblanco this issue should be resolved with the latest release

https://github.com/henalbrod/Blazor.Auth0/releases/tag/v2.0.0-Preview2

**Closed as completed** 2019-11-04 02:28 UTC
